# Generated by Django 3.2.5 on 2021-07-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=150, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'brands',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=150, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transmision', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transmision',
                'db_table': 'transmission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=200)),
                ('costo', models.FloatField()),
                ('motor', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=50)),
                ('torque', models.CharField(max_length=50)),
                ('cilindrada', models.CharField(max_length=50)),
                ('año_fabricacion', models.IntegerField()),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('estado', models.CharField(max_length=15)),
                ('imagen', models.ImageField(default='-', max_length=255, upload_to='autos')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo')),
                ('id_transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transmision')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
                'db_table': 'cars',
                'ordering': ['id_marca'],
            },
        ),
    ]
